sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 86515305
  s3:
    region: us-west-1
    access-key-id: AKIAZI2LIQAV6XCFZSQG
    access-key-secret: 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
    bucket-name: jackysky-bucket
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
